import type { Episode } from './types'

export interface SeasonMeta {
  season: number
  episodeCount: number
  year: string
  synopsis: string
  poster: string
  trailerUrl: string
  genres: string
  duration: string
}

const TRAILER = 'https://www.dailymotion.com/crawler/video/x8pzmh7'

export const SEASONS: SeasonMeta[] = [
  {
    season: 1,
    episodeCount: 11,
    year: '2013',
    synopsis: 'Aventuras caóticas y realidades alternativas en la primera entrega de la serie. Rick se sumerge en un mundo pseudo-real entre multiversos, mientras Summer se une a Beth Espacial en su lucha contra la malvada Federación Galáctica.',
    poster: 'https://images.justwatch.com/poster/309176070/s718/temporada-1.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedia, Ciencia ficción, Animación',
    duration: '22 min'
  },
  {
    season: 2,
    episodeCount: 10,
    year: '2015',
    synopsis: 'Rick y Morty han decidido descongelar el tiempo y tienen que enfrentarse a parásitos alienígenas, Jerrys alternativos y una dimensión decadente, posiblemente inexistente.',
    poster: 'https://images.justwatch.com/poster/309176178/s718/temporada-2.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedia, Ciencia ficción, Animación',
    duration: '23 min'
  },
  {
    season: 3,
    episodeCount: 10,
    year: '2017',
    synopsis: 'Rick y Morty viajan a Atlantis y se toman un tiempo para descansar, además Rick se convierte en un pepinillo y se enfrenta al presidente.',
    poster: 'https://images.justwatch.com/poster/309176032/s718/temporada-3.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedia, Ciencia ficción, Animación',
    duration: '22 min'
  },
  {
    season: 4,
    episodeCount: 10,
    year: '2019',
    synopsis: 'El genio Rick y su nieto Morty continúan realizando viajes interdimensionales que desafían al tiempo y al espacio.',
    poster: 'https://images.justwatch.com/poster/309176182/s718/temporada-4.jpg',
    trailerUrl: TRAILER,
    genres: 'Animación, Comedia, Ciencia ficción',
    duration: '22 min'
  },
  {
    season: 5,
    episodeCount: 10,
    year: '2021',
    synopsis: 'Rick, Morty y la fam están de vuelta con diez episodios totalmente nuevos. Sexo, romance, monstruos testiculares... un tipo llamado Sr. Nimbus...',
    poster: 'https://images.justwatch.com/poster/247615255/s718/temporada-5.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedia, Ciencia ficción, Animación',
    duration: '22 min'
  },
  {
    season: 6,
    episodeCount: 10,
    year: '2022',
    synopsis: '¡Es la sexta temporada y Rick y Morty están de vuelta! ¿Lograrán recuperarse para más aventuras o serán arrastrados por un océano de orina?',
    poster: 'https://images.justwatch.com/poster/309176033/s718/temporada-6.jpg',
    trailerUrl: TRAILER,
    genres: 'Animación, Comedia, Ciencia ficción',
    duration: '22 min'
  },
  {
    season: 7,
    episodeCount: 10,
    year: '2023',
    synopsis: 'Rick y Morty han vuelto y suenan más que nunca. Es la séptima temporada, y las posibilidades son infinitas. Probablemente haya menos cabreo que en la temporada pasada.',
    poster: 'https://images.justwatch.com/poster/309176189/s718/temporada-7.jpg',
    trailerUrl: TRAILER,
    genres: 'Animación, Comedia, Ciencia ficción',
    duration: '22 min'
  },
  {
    season: 8,
    episodeCount: 10,
    year: '2025',
    synopsis: 'Más caos y la característica mirada mordaz a la condición humana. El científico alcohólico más brillante del multiverso regresa con Morty a bordo para una nueva tanda de 10 aventuras.',
    poster: 'https://images.justwatch.com/poster/333290761/s718/temporada-8.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedia, Ciencia ficción, Animación',
    duration: '23 min'
  },
  {
    season: 9,
    episodeCount: 10,
    year: '2026',
    synopsis: 'Season 9 is all certified bangers. No AI slop! Just Grade A organic slop, made by real humans with real human traits like back hair and cysts.',
    poster: 'https://images.justwatch.com/poster/343264500/s718/temporada-9.jpg',
    trailerUrl: TRAILER,
    genres: 'Animación, Comedia, Ciencia ficción',
    duration: '22 min'
  }
]

export const SEASONS_EN: SeasonMeta[] = [
  {
    season: 1,
    episodeCount: 11,
    year: '2013',
    synopsis: 'Chaotic adventures and alternate realities in the first installment of the series. Rick immerses himself in a pseudo-real world across multiverses, while Summer joins Space Beth in her fight against the evil Galactic Federation.',
    poster: 'https://images.justwatch.com/poster/309176070/s718/temporada-1.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedy, Sci-fi, Animation',
    duration: '22 min'
  },
  {
    season: 2,
    episodeCount: 10,
    year: '2015',
    synopsis: 'Rick and Morty decide to thaw time and must face alien parasites, alternate Jerrys, and a decaying, possibly non-existent dimension.',
    poster: 'https://images.justwatch.com/poster/309176178/s718/temporada-2.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedy, Sci-fi, Animation',
    duration: '23 min'
  },
  {
    season: 3,
    episodeCount: 10,
    year: '2017',
    synopsis: 'Rick and Morty travel to Atlantis and take some time to rest. Rick also becomes a pickle and faces the president.',
    poster: 'https://images.justwatch.com/poster/309176032/s718/temporada-3.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedy, Sci-fi, Animation',
    duration: '22 min'
  },
  {
    season: 4,
    episodeCount: 10,
    year: '2019',
    synopsis: 'The genius Rick and his grandson Morty continue their interdimensional travels that defy time and space.',
    poster: 'https://images.justwatch.com/poster/309176182/s718/temporada-4.jpg',
    trailerUrl: TRAILER,
    genres: 'Animation, Comedy, Sci-fi',
    duration: '22 min'
  },
  {
    season: 5,
    episodeCount: 10,
    year: '2021',
    synopsis: 'Rick, Morty and the fam are back with ten brand new episodes. Sex, romance, testicle monsters... a guy named Mr. Nimbus...',
    poster: 'https://images.justwatch.com/poster/247615255/s718/temporada-5.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedy, Sci-fi, Animation',
    duration: '22 min'
  },
  {
    season: 6,
    episodeCount: 10,
    year: '2022',
    synopsis: 'It\'s season six and Rick and Morty are back! Will they recover for more adventures or be dragged through an ocean of urine?',
    poster: 'https://images.justwatch.com/poster/309176033/s718/temporada-6.jpg',
    trailerUrl: TRAILER,
    genres: 'Animation, Comedy, Sci-fi',
    duration: '22 min'
  },
  {
    season: 7,
    episodeCount: 10,
    year: '2023',
    synopsis: 'Rick and Morty are back and louder than ever. It\'s the seventh season, and the possibilities are infinite. Probably less grumpy than last season.',
    poster: 'https://images.justwatch.com/poster/309176189/s718/temporada-7.jpg',
    trailerUrl: TRAILER,
    genres: 'Animation, Comedy, Sci-fi',
    duration: '22 min'
  },
  {
    season: 8,
    episodeCount: 10,
    year: '2025',
    synopsis: 'More chaos and the signature sharp look at the human condition. The most brilliant alcoholic scientist in the multiverse returns with Morty on board for a new batch of 10 adventures.',
    poster: 'https://images.justwatch.com/poster/333290761/s718/temporada-8.jpg',
    trailerUrl: TRAILER,
    genres: 'Comedy, Sci-fi, Animation',
    duration: '23 min'
  },
  {
    season: 9,
    episodeCount: 10,
    year: '2026',
    synopsis: 'Season 9 is all certified bangers. No AI slop! Just Grade A organic slop, made by real humans with real human traits like back hair and cysts.',
    poster: 'https://images.justwatch.com/poster/343264500/s718/temporada-9.jpg',
    trailerUrl: TRAILER,
    genres: 'Animation, Comedy, Sci-fi',
    duration: '22 min'
  }
]

const S6_EPISODES: [string, string][] = [
  ['Solaricks', '2022-09-04'],
  ['Rick: una Mort plena', '2022-09-11'],
  ['Gemelinstinto Béthico', '2022-09-18'],
  ['La familia nocturna', '2022-09-25'],
  ['DeSmithno final', '2022-10-02'],
  ['Morque JuRícksico', '2022-10-09'],
  ['La Chaqueta MetáRicka', '2022-10-16'],
  ['Una mierdapia peligrosa', '2022-11-20'],
  ['Un Rick en la Morty del rey Morturo', '2022-11-27'],
  ['¡SocorRick! Ya es Mortidad', '2022-12-11'],
]

const S7_EPISODES: [string, string][] = [
  ['Cómo Ojetesucio recuperó el ojete', '2023-10-15'],
  ['Tú a Jerron y yo a Rickifornia', '2023-10-22'],
  ['Air Force Wong', '2023-10-29'],
  ["That's Amorty", '2023-11-05'],
  ['Sin Rickmort', '2023-11-12'],
  ['El Rickielo... mórtimamente', '2023-11-19'],
  ['Wet Kuat Amortican Summer', '2023-11-26'],
  ['El origen de los Numericons: la película', '2023-12-03'],
  ['Mort: Ragnarick', '2023-12-10'],
  ['Mortifer', '2023-12-17'],
]

const S8_EPISODES: [string, string][] = [
  ['El verano de todos los miedos', '2025-05-25'],
  ['Valkyrick', '2025-06-01'],
  ['El Rick, el Mort y el Feo', '2025-06-08'],
  ['La Última Tentación de Jerry', '2025-06-15'],
  ['Criomuerte a Rickver', '2025-06-22'],
  ['El Rick-curioso caso de Bethjamin Button', '2025-06-29'],
  ['Más Rick que la ficción', '2025-07-06'],
  ['Nomortland', '2025-07-13'],
  ['Morty Papi', '2025-07-20'],
  ['Rick el caliente', '2025-07-27'],
]

const S9_EPISODES: [string, string][] = [
  ['Episodio 1', '2026-05-24'],
  ['Episodio 2', '2026-05-31'],
  ['Episodio 3', '2026-06-07'],
  ['Episodio 4', '2026-06-14'],
  ['Episodio 5', '2026-06-21'],
  ['Episodio 6', '2026-06-28'],
  ['Episodio 7', '2026-07-05'],
  ['Episodio 8', '2026-07-12'],
  ['Episodio 9', '2026-07-19'],
  ['Episodio 10', '2026-07-26'],
]

function makeEpisode(
  id: number,
  name: string,
  airDate: string,
  season: number,
  ep: number,
): Episode {
  const epStr = `S${String(season).padStart(2, '0')}E${String(ep).padStart(2, '0')}`
  return {
    id,
    name,
    air_date: airDate,
    episode: epStr,
    characters: [],
    url: `https://rickandmortyapi.com/api/episode/missing-${id}`,
    created: `${airDate}T00:00:00.000Z`,
  }
}

function buildSeason(episodes: [string, string][], season: number, startId: number): Episode[] {
  return episodes.map(([name, date], i) => makeEpisode(startId + i, name, date, season, i + 1))
}

export const MISSING_EPISODES: Episode[] = [
  ...buildSeason(S6_EPISODES, 6, 52),
  ...buildSeason(S7_EPISODES, 7, 62),
  ...buildSeason(S8_EPISODES, 8, 72),
  ...buildSeason(S9_EPISODES, 9, 82),
]

export const SPANISH_TITLES: Record<string, string> = {
  'S01E01': 'Piloto',
  'S01E02': 'El cortador de césped',
  'S01E03': 'Parque Anatomía',
  'S01E04': 'M. Night Shaym-Aliens!',
  'S01E05': 'Meeseeks y destrucción',
  'S01E06': 'Rick Poción #9',
  'S01E07': 'Criando a Gazorpazor',
  'S01E08': 'Televisiones malignas',
  'S01E09': 'Algo malvado viene así',
  'S01E10': 'Encuentros cercanos del tipo Rick',
  'S01E11': 'Negocios Ricksosos',
  'S02E01': 'Un Rickle en el tiempo',
  'S02E02': 'Mortynight Run',
  'S02E03': 'Asimilación autoerótica',
  'S02E04': 'Totalmente Rick-llado',
  'S02E05': 'Ponte Schwifty',
  'S02E06': 'Los Ricks deben estar locos',
  'S02E07': 'Grandes problemas en Little Sanchez',
  'S02E08': 'Cable interdimensional 2: Tentando al destino',
  'S02E09': 'Mira quién purga ahora',
  'S02E10': 'Los Squanchers de la boda',
  'S03E01': 'El rescate Rickstático',
  'S03E02': 'Rickmanceando la piedra',
  'S03E03': 'Pepinillo Rick',
  'S03E04': 'Vindicators 3: El retorno de Worldender',
  'S03E05': 'La conspiración del Whirly Dirly',
  'S03E06': 'Descanso y Ricklajación',
  'S03E07': 'Cuentos de la Ciudadela',
  'S03E08': 'Los explosores de mente de Morty',
  'S03E09': 'El ABC de Beth',
  'S03E10': 'La Rickchuriana Mortidato',
  'S04E01': 'Edge of Tomorty: Rick Die Rickpeat',
  'S04E02': 'El viejo y los asientos',
  'S04E03': 'Uno más sobre el Mortycu',
  'S04E04': 'Garra y Acaparador: Especial Ricktimo de Morty',
  'S04E05': 'Rattlestar Ricklactica',
  'S04E06': 'Nunca Rickando a Morty',
  'S04E07': 'Promortyus',
  'S04E08': 'El episodio del tanque de ácido',
  'S04E09': 'Childrick of Mort',
  'S04E10': 'Star Mort: El retorno de Jerri',
  'S05E01': 'Mort Cena Rick Andre',
  'S05E02': 'Mortyplicidad',
  'S05E03': 'Un Morty conveniente',
  'S05E04': 'Spray de Rickdependencia',
  'S05E05': 'Grickfitti Amorticano',
  'S05E06': 'Thanksploitation de Rick y Morty',
  'S05E07': 'Gotron Jerrysis Rickvangelion',
  'S05E08': 'Rickternal Friendshine of the Spotless Mort',
  'S05E09': 'Olvidando a Sarick Mortshall',
  'S05E10': 'Rickmurai Jack',
  'S06E01': 'Solaricks',
  'S06E02': 'Rick: una Mort plena',
  'S06E03': 'Gemelinstinto Béthico',
  'S06E04': 'La familia nocturna',
  'S06E05': 'DeSmithno final',
  'S06E06': 'Morque JuRícksico',
  'S06E07': 'La Chaqueta MetáRicka',
  'S06E08': 'Una mierdapia peligrosa',
  'S06E09': 'Un Rick en la Morty del rey Morturo',
  'S06E10': '¡SocorRick! Ya es Mortidad',
  'S07E01': 'Cómo Ojetesucio recuperó el ojete',
  'S07E02': 'Tú a Jerron y yo a Rickifornia',
  'S07E03': 'Fuerza Aérea Wong',
  'S07E04': 'Eso es Amorte',
  'S07E05': 'Sin Rickmort',
  'S07E06': 'El Rickielo... mórtimamente',
  'S07E07': 'Wet Kuat Amortican Summer',
  'S07E08': 'El origen de los Numericons',
  'S07E09': 'Mort: Ragnarick',
  'S07E10': 'Mortifer',
  'S08E01': 'El verano de todos los miedos',
  'S08E02': 'Valkyrick',
  'S08E03': 'El Rick, el Mort y el Feo',
  'S08E04': 'La última tentación de Jerry',
  'S08E05': 'Criomuerte a Rickver',
  'S08E06': 'El curioso caso de Bethjamin Button',
  'S08E07': 'Más Rick que la ficción',
  'S08E08': 'Nomortland',
  'S08E09': 'Morty Papi',
  'S08E10': 'Rick el caliente',
  'S09E01': 'Episodio 1',
  'S09E02': 'Episodio 2',
  'S09E03': 'Episodio 3',
  'S09E04': 'Episodio 4',
  'S09E05': 'Episodio 5',
  'S09E06': 'Episodio 6',
  'S09E07': 'Episodio 7',
  'S09E08': 'Episodio 8',
  'S09E09': 'Episodio 9',
  'S09E10': 'Episodio 10',
}

export const ENGLISH_TITLES: Record<string, string> = {
  'S01E01': 'Pilot',
  'S01E02': 'Lawnmower Dog',
  'S01E03': 'Anatomy Park',
  'S01E04': 'M. Night Shaym-Aliens!',
  'S01E05': 'Meeseeks and Destroy',
  'S01E06': 'Rick Potion #9',
  'S01E07': 'Raising Gazorpazorp',
  'S01E08': 'Rixty Minutes',
  'S01E09': 'Something Ricked This Way Comes',
  'S01E10': 'Close Rick-counters of the Rick Kind',
  'S01E11': 'Ricksy Business',
  'S02E01': 'A Rickle in Time',
  'S02E02': 'Mortynight Run',
  'S02E03': 'Auto Erotic Assimilation',
  'S02E04': 'Total Rickall',
  'S02E05': 'Get Schwifty',
  'S02E06': 'The Ricks Must Be Crazy',
  'S02E07': 'Big Trouble in Little Sanchez',
  'S02E08': 'Interdimensional Cable 2: Tempting Fate',
  'S02E09': 'Look Who\'s Purging Now',
  'S02E10': 'The Wedding Squanchers',
  'S03E01': 'The Rickshank Rickdemption',
  'S03E02': 'Rickmancing the Stone',
  'S03E03': 'Pickle Rick',
  'S03E04': 'Vindicators 3: The Return of Worldender',
  'S03E05': 'The Whirly Dirly Conspiracy',
  'S03E06': 'Rest and Ricklaxation',
  'S03E07': 'The Ricklantis Mixup',
  'S03E08': 'Morty\'s Mind Blowers',
  'S03E09': 'The ABC\'s of Beth',
  'S03E10': 'The Rickchurian Mortydate',
  'S04E01': 'Edge of Tomorty: Rick Die Rickpeat',
  'S04E02': 'The Old Man and the Seat',
  'S04E03': 'One Crew over the Crewcoo\'s Morty',
  'S04E04': 'Claw and Hoarder: Special Ricktim\'s Morty',
  'S04E05': 'Rattlestar Ricklactica',
  'S04E06': 'Never Ricking Morty',
  'S04E07': 'Promortyus',
  'S04E08': 'The Vat of Acid Episode',
  'S04E09': 'Childrick of Mort',
  'S04E10': 'Star Mort Rickturn of the Jerri',
  'S05E01': 'Mort Dinner Rick Andre',
  'S05E02': 'Mortyplicity',
  'S05E03': 'A Rickconvenient Mort',
  'S05E04': 'Rickdependence Spray',
  'S05E05': 'Amortycan Grickfitti',
  'S05E06': 'Rick & Morty\'s Thanksploitation Spectacular',
  'S05E07': 'Gotron Jerrysis Rickvangelion',
  'S05E08': 'Rickternal Friendshine of the Spotless Mort',
  'S05E09': 'Forgetting Sarick Mortshall',
  'S05E10': 'Rickmurai Jack',
  'S06E01': 'Solaricks',
  'S06E02': 'Rick: A Mort Well Lived',
  'S06E03': 'Bethic Twinstic',
  'S06E04': 'Night Family',
  'S06E05': 'Final DeSmithation',
  'S06E06': 'Juricksic Mort',
  'S06E07': 'Full Meta Jackrick',
  'S06E08': 'Analyze Piss',
  'S06E09': 'A Rick in King Mortur\'s Mort',
  'S06E10': 'Ricktional Mortpoon\'s Rickmas Mortcation',
  'S07E01': 'How Poopy Got His Poop Back',
  'S07E02': 'The Jerrick Trap',
  'S07E03': 'Air Force Wong',
  'S07E04': `That's Amorte`,
  'S07E05': 'Unmortricken',
  'S07E06': 'Rickfending Your Mort',
  'S07E07': 'Wet Kuat Amortican Summer',
  'S07E08': 'Rise of the Numbericons: The Movie',
  'S07E09': 'Mort: Ragnarick',
  'S07E10': 'Fear No Mort',
  'S08E01': 'Summer of All Fears',
  'S08E02': 'Valkyrick',
  'S08E03': 'The Rick, The Mort & The Ugly',
  'S08E04': 'The Last Temptation of Jerry',
  'S08E05': 'Cryo Mort a Rickver',
  'S08E06': 'The Curicksous Case of Bethjamin Button',
  'S08E07': 'Ricker Than Fiction',
  'S08E08': 'Nomortland',
  'S08E09': 'Morty Daddy',
  'S08E10': 'Hot Rick',
  'S09E01': 'There\'s Something About Morty',
  'S09E02': 'Ricks Days, Seven Nights',
  'S09E03': 'Rick Fu Hustle',
  'S09E04': 'A Ricker Runs Through It',
  'S09E05': 'Jer Bud',
  'S09E06': 'Erickerhead',
  'S09E07': 'MortGully: The Last Rickforest',
  'S09E08': 'Rickuiem Mort a Dream',
  'S09E09': 'Salute Your Morts',
  'S09E10': 'Field of Dreams',
}
